# carrega configuracoes das posicoes dos monitores
#/usr/bin/xmodmap /home/marvin/.config/xorg_configs/Xmodmap &
#/home/marvin/.config/xorg_configs/default.sh &
#/usr/bin/nm-applet & 
# inicia Qtile
exec qtile start 
