[global]
    monitor = 1
    follow = mouse
    geometry = "320x5-12+42"
    indicate_hidden = yes
    shrink = no
    transparency = 30
    notification_height = 0
    separator_height = 2
    padding = 10
    horizontal_padding = 10
    frame_width = 1
    separator_color = frame
    sort = yes
    idle_threshold = 120
    font = Source Sans Pro 10
    line_height = 0
    markup = full
    format = "<span foreground='#f3f4f5'><b>%s %p</b></span>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    word_wrap = yes
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes
    icon_position = left
    max_icon_size = 32
    icon_path = /usr/share/icons/Adwaita/16x16/devices:/usr/share/icons/Adwaita/16x16/places/

    dmenu = /usr/bin/rofi -dmenu -p dunst:

      #  browser = /usr/bin/firefox -new-tab
    browser = /usr/bin/google-chrome-stable 

    always_run_script = true

    sticky_history = yes
    history_length = 20
    always_run_script = true
    startup_notification = false
    verbosity = mesg
    corner_radius = 0
    ignore_dbusclose = false
    force_xinerama = false

    # Actions
    mouse_left_click = open_url, close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all

[shortcuts]
    close = ctrl+space
    history = ctrl+shift+space
    history = ctrl+grave
    context = ctrl+shift+period

[urgency_low]
    background = "#0a091c"
    foreground = "#a8a8a8"
    frame_color = "#0a091c"
    timeout = 5

[urgency_normal]
    background = "#070614"
    foreground = "#a8a8a8"
    frame_color = "#070614"
    timeout = 10

[urgency_critical]
    background = "#ff5555"
    foreground = "#f0e0e0"
    frame_color = "#ff5555"
    timeout = 0
