#! /bin/sh
#Loads keybind Server
pkill -9 -f sxhkd
sxhkd &

#Configures Polybar
pgrep -f polybar >/dev/null && pkill -9 -f polybar
polybar default &

#bspwm configurations
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5
bspc config bottom_padding 18
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#383C36"
bspc config focused_border_color "#11840b"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a vscode-color-ui state=floating
bspc rule -a font-manager state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Set Mouse pointer to arrow
xsetroot -cursor_name left_ptr &

#Wallpaper
nitrogen --restore &

#Window Composer
pgrep -f compton >/dev/null && pkill -9 -f compton >/dev/null
compton -bcC &

#Start terminal
pgrep -f xfce4-terminal >/dev/null || xfce4-terminal &

#Redshift
pgrep -f redshift >/dev/null && pkill -9 -f redshift
redshift -c ~/.config/redshift/redshift.conf &

#Green clip
pgrep -f greenclip >/dev/null && pkill -9 -f greenclip
greenclip daemon &
