#! /bin/bash

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")

# Debug:
# exec 3>&1 4>&2 >$log 2>&1
# info=$(xwininfo -id $wid)
# echo "=========================================" 
# echo "wid=$wid class=$class instance=$instance" 
# echo "Title = $title" 
# echo "Info = $info" 
# echo "=========================================" 
# exec 1>&3 2>&4

case "$title" in
 "Emulator")
     echo "desktop=^5"
     ;; 
 "Android Studio")
     echo "desktop=^4"
     ;;
 "Tip of the Day")
     echo "desktop=^4"
     ;;
esac

