#! /bin/bash

log=~/.config/bspwm/window.log

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")

Debug:
info=$(xwininfo -id $wid)
exec 3>&1 4>&2 >>$log 2>&1
echo "===== [wid=$wid class=$class instance=$instance] =====" 
echo "Title = $title" 
echo "Info = $info" 
echo "------------------------------------------------------" 
exec 1>&3 2>&4

case "$class" in
  "Chromium")
    echo "desktop=^3"
esac

case "$title" in
  "Emulator")
    echo "desktop=^5"
    echo "state=floating" #Will remember last position
     ;; 
   "IntelliJ IDEA"|"Android Studio")
    echo "desktop=^4"
    echo "state=fullscreen"
     ;; 
  "Tip of the Day")
    echo "desktop=^4"
    echo "state=floating" #Will remember last position
     ;;
  "Mozilla Firefox")
    echo "desktop=^2"
     ;;
esac

